name: Generator
main: me.JamieSinn.Generator.Generator
version: 1.1
author: JamieSinn
description: Generator for buildings.
commands:
  gcube:
    description: Generates a cube
  ghcube:
    description: Generates a hollow cube
